<?xml version="1.0"?>
<package format="3">
  <name>cas_ec15_pyserial</name>
  <version>0.1.0</version>
  <description>CAS EC-15 RS-232 reader and ROS 2 weight publisher.</description>
  <maintainer email="nayana224@users.noreply.github.com">Inpyo Lee</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>python3-serial</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
